import { Tutor } from './tutor';
export const tutorslist: Tutor[] =[
    {
        id: 1,
        name: 'Srikar Marupaka',
        price: 30,
        description: 'Native English speaker passionate about catering your lessons to suit your personal objectives whether they are to learn English asa  be ginner, improve your current level, pass a global language exam or practice English language for Business.',
        students: 129,
        lessons: 269,
        experience: 6,
        language: ['Telugu','English'],
        rating: 4.6,
        ratingcount:100,
        certification:['CELTA','English'],
        recomended:true,
        subjects:['telugu', 'English', 'computers'],
        gender:'male',
        age:28,
        currentposition:'Data Scientist'
    },
    {
        id: 2,
        name: 'Sharma Marupaka',
        price: 30,
        description: 'Native English speaker passionate about catering your lessons to suit your personal objectives whether they are to learn English asa  be ginner, improve your current level, pass a global language exam or practice English language for Business.',
        students: 129,
        lessons: 269,
        experience: 6,
        language: ['Arabic','English'],
        rating: 4.6,
        ratingcount:100,
        
        certification:['CELTA','English'],
        recomended:true,
        subjects:['telugu', 'English', 'computers'],
        gender:'male',
        age:28,
        currentposition:'Data Scientist'
    },
    {
        id: 3,
        name: 'Srikar Marupaka',
        price: 30,
        description: 'Native English speaker passionate about catering your lessons to suit your personal objectives whether they are to learn English asa  be ginner, improve your current level, pass a global language exam or practice English language for Business.',
        students: 129,
        lessons: 269,
        experience: 6,
        language: ['Arabic','English'],
        rating: 4.6,
        ratingcount:100,
        certification:['CELTA','English'],
        recomended:true,
        subjects:['telugu', 'English', 'computers'],
        gender:'male',
        age:28,
        currentposition:'Data Scientist'
        
    },
    {
        id: 4,
        name: 'Srikar Marupaka',
        price: 30,
        description: 'Native English speaker passionate about catering your lessons to suit your personal objectives whether they are to learn English asa  be ginner, improve your current level, pass a global language exam or practice English language for Business.',
        students: 129,
        lessons: 269,
        experience: 6,
        language: ['Arabic','English'],
        rating: 4.6,
        ratingcount:100,
        certification:['CELTA','English'],
        recomended:true,
        subjects:['telugu', 'English', 'computers'],
        gender:'male',
        age:28,
        currentposition:'Data Scientist'
    },
]